name: CICD Pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install deps
        run: npm ci

      - name: Build Angular
        run: npm run build --if-present

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    environment: test
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Auth GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build Docker image
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT }}/frontend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend-test \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/frontend:${{ github.sha }} \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated
